spring.application.name=placement-management-api

spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:23535/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SicQZXKrNlFKvxqtYgDUDdyGExIhLjij

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
