spring.application.name=placement-management-api

# Database (Railway MySQL - direct connection)
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:23535/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SicQZXKrNlFKvxqtYgDUDdyGExIhLjij

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server port (VERY IMPORTANT for Railway)
server.port=${PORT:8080}
